In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a 1-dimensional array using arange()
# This will generate numbers from 0 up to (but not including) 12
one_d_array = np.arange(12)
print("1-D Array:")
print(one_d_array)

1-D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
# Reshape the 1-dimensional array into a 2-dimensional array (e.g., 3 rows, 4 columns)
two_d_array = one_d_array.reshape(3, 4)
print("\n2-D Array:")
print(two_d_array)
print("Rank:", two_d_array.ndim)


2-D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Rank: 2


In [7]:
arr = np.arange(10, 0, -2)
print(arr)
print(arr.dtype, arr)

[10  8  6  4  2]
int32 [10  8  6  4  2]


In [8]:
np.random.rand(3,4)

array([[0.34393449, 0.34085191, 0.81067286, 0.67925439],
       [0.5271678 , 0.93628086, 0.53948192, 0.44043885],
       [0.85060165, 0.82967485, 0.2662443 , 0.52059347]])

In [9]:
np.random.randn(3,4)

array([[-0.050039  ,  0.69245274, -0.76599026,  0.27706546],
       [-2.69308406,  1.3431805 ,  1.08515001,  0.7230047 ],
       [ 0.72126904,  0.10820948, -0.72325205, -0.37778239]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
a.shape

(3, 4)

In [15]:
a.ndim

2

In [16]:
a.size

12

In [19]:
d=np.ones((3,4))
print(d)
type(d)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [23]:
e=np.full((3,4), np.pi)
e

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [24]:
#linspace function returns an array containing a specific number of points 
#evenly distributed between two values (note that the maximum value is included, contrary to arange):
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [26]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [27]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


In [28]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


In [29]:
g2[1, 2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [30]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [32]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [33]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [34]:
m < 25  # equivalent to m < [25, 25, 25, 25]

array([ True,  True, False, False])

In [35]:
m[m < 25]

array([20, -5])

In [36]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


In [37]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [39]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [40]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [41]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

In [42]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [43]:
# SEE FROM ARRAY INDEXING IN TUTORIAL

In [44]:
A = np.array([
    [1, 5, 9],
    [3, 12, 7],
    [8, 4, 15]
])

T = 8


In [46]:
A>T

array([[False, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [47]:
A[A>T]

array([ 9, 12, 15])

In [48]:
A[A>T]=T
print(A)

[[1 5 8]
 [3 8 7]
 [8 4 8]]


In [56]:
arr = np.array([4, -1, 7, -3, 0, 5])

arr[arr < 0] = 0
print(arr)

[4 0 7 0 0 5]


In [49]:
T = np.array([5, 10, 6])  # one threshold per column
A = np.minimum(A, T)

In [50]:
print(A)

[[1 5 6]
 [3 8 6]
 [5 4 6]]


In [51]:
B = np.clip(A, None, T)
print(B)

[[1 5 6]
 [3 8 6]
 [5 4 6]]


In [ ]:
T_Low=np.array([2])     # BROADCASTING EXAMPLE
T_High=np.array([6])
C=np.clip(B, T_Low, T_High)

In [53]:
print(C)

[[2 5 6]
 [3 6 6]
 [5 4 6]]


In [58]:
A = np.array([
    [12, 5],
    [3, 1],
    [15, 8]
])

rows = A[:, 0] > 10
print(A[rows])

[[12  5]
 [15  8]]


In [59]:
arr = np.array([1, 2, 3, 4, 5, 6])

mask = arr % 2 == 0   # even numbers
odd_values = arr[~mask]
print(odd_values)

[1 3 5]


In [ ]:
A = np.array([
    [3, 5, 7],
    [2, 6, 9],
    [8, 1, 4]
])

n = A.shape[0]
rows, cols = np.indices((n, n))
print(rows, cols)
A[rows < cols] = 0   # upper diagonal entries     # try rows==cols, rows > cols

print(A)

[[0 0 0]
 [1 1 1]
 [2 2 2]] [[0 1 2]
 [0 1 2]
 [0 1 2]]
[[3 0 0]
 [2 6 0]
 [8 1 4]]


In [ ]:
# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:\n", arr)

# Example 1: Default k (k=0)
# Elements below the main diagonal are set to zero.
result_default = np.triu(arr)
print("\nUpper triangle (default k=0):\n", result_default)

# Example 2: k=1 
# Elements below the diagonal and the main diagonal are set to zero.
result_k_1 = np.triu(arr, k=1)
print("\nUpper triangle (k=1):\n", result_k_1)

# Example 3: k=-1 
# Elements below the diagonal below the main diagonal are set to zero.
result_k_neg1 = np.triu(arr, k=-1)
print("\nUpper triangle (k=-1):\n", result_k_neg1)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Upper triangle (default k=0):
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Upper triangle (k=1):
 [[0 2 3]
 [0 0 6]
 [0 0 0]]

Upper triangle (k=-1):
 [[1 2 3]
 [4 5 6]
 [0 8 9]]


In [66]:
# Example 4: Using with a different shape array (e.g., non-square)
arr_rect = np.array([[10, 11, 12, 13],
                     [14, 15, 16, 17],
                     [18, 19, 20, 21]])

print("\nOriginal rectangular array:\n", arr_rect)

result_rect = np.triu(arr_rect, k=0)
print("\nUpper triangle of rectangular array (k=0):\n", result_rect)


Original rectangular array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Upper triangle of rectangular array (k=0):
 [[10 11 12 13]
 [ 0 15 16 17]
 [ 0  0 20 21]]


In [77]:
# REMOVE OUTLIER FUNCTION: remove_outliers(data, cutoff)

def remove_outliers(data, cutoff):
    """
    Remove outliers from a 1D dataset using z-score cutoff.

    Parameters:
        data (array-like): Input numeric dataset.
        cutoff (float): Threshold for z-score. Values with |z| > cutoff are removed.
    
    Returns:
        np.ndarray: Cleaned dataset with outliers removed.
    """
    
    data = np.asarray(data)  # make sure it's a NumPy array

    mean = np.mean(data)
    std = np.std(data)

    # avoid division by zero
    if std == 0:
        return data

    z_scores = (data - mean) / std
    print(z_scores)
    # boolean mask: keep values whose z-score magnitude ≤ cutoff
    mask = np.abs(z_scores) <= cutoff

    return data[mask]

In [78]:
data = np.array([10, 12, 11, 9, 13, 100, 8, 11])
cleaned = remove_outliers(data, cutoff=2.5)

print(cleaned)

[-0.39678345 -0.32924584 -0.36301464 -0.43055225 -0.29547703  2.64240891
 -0.46432105 -0.36301464]
[10 12 11  9 13  8 11]


In [69]:
data = np.array([10, 12, 11, 9, 13, 100, 8])

mean = data.mean()
std = data.std()

mask = np.abs((data - mean) / std) <= 2  # keep only non-outliers
cleaned = data[mask]

print(cleaned)

[10 12 11  9 13  8]


In [70]:
def remove_outliers_iqr(data):
    """
    Remove outliers from a 1D dataset using the IQR rule:
    Keep values within [Q1 - 1.5*IQR, Q3 + 1.5*IQR]

    Parameters:
        data (array-like): Numeric 1D dataset.

    Returns:
        np.ndarray: Cleaned dataset with outliers removed.
    """
    data = np.asarray(data)

    # Compute Q1, Q3, and IQR
    Q1 = np.percentile(data, 25)
    Q3 = np.percentile(data, 75)
    IQR = Q3 - Q1

    # Bounds for acceptable values
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Boolean mask for values within the bounds
    mask = (data >= lower_bound) & (data <= upper_bound)

    return data[mask]

In [71]:
data = np.array([10, 12, 11, 9, 13, 100, 8, 11])

cleaned = remove_outliers_iqr(data)
print(cleaned)

[10 12 11  9 13  8 11]


In [16]:
def remove_outliers_iqr_df(df, columns=None):
    """
    Remove outliers from a pandas DataFrame using the IQR rule.
    A row is removed if ANY of the specified columns contains an outlier.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        columns (list or None): Numeric columns to check.
                                If None, all numeric columns are used.

    Returns:
        pd.DataFrame: DataFrame with outlier rows removed.
    """
    
    if columns is None:
        columns = df.select_dtypes(include=[np.number]).columns.tolist()
    
    cleaned_df = df.copy()
    
    for col in columns:
        Q1 = cleaned_df[col].quantile(0.25)
        Q3 = cleaned_df[col].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Keep only rows within the bounds
        mask = (cleaned_df[col] >= lower_bound) & (cleaned_df[col] <= upper_bound)
        cleaned_df = cleaned_df[mask]
    
    return cleaned_df



df = pd.DataFrame({
    "age": [25, 27, 29, 31, 300, 28],
    "income": [50, 52, 49, 53, 51, 2000]
})

cleaned = remove_outliers_iqr_df(df)
print(cleaned)

   age  income
0   25      50
1   27      52
2   29      49
3   31      53


In [4]:
def remove_outliers_zscore_df(df, cutoff=3.0, columns=None):
    """
    Remove outliers from a DataFrame using Z-score.
    
    A row is removed if ANY of the chosen columns
    has |z| > cutoff for that column.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        cutoff (float): Z-score threshold, default = 3.0.
        columns (list or None):
            List of numeric columns to check.
            If None, all numeric columns are used.

    Returns:
        pd.DataFrame: Cleaned DataFrame with outlier rows removed.
    """
    
    if columns == None:
        columns = df.select_dtypes(include=[np.number]).columns.tolist()

    df_clean = df.copy()
    print(columns)
    # Calculate mean and std per column
    means = df_clean[columns].mean()
    stds = df_clean[columns].std()
    print(means)
    print(stds)
    # Avoid division by zero
    stds_replaced = stds.replace(0, np.nan)

    # Compute Z-scores
    zscores = (df_clean[columns] - means) / stds_replaced
    print(zscores)
    # Keep rows where ALL columns satisfy |z| <= cutoff
    mask = (np.abs(zscores) <= cutoff).all(axis=1)

    return df_clean[mask]

df = pd.DataFrame({
    "age": [25, 27, 29, 31, 300, 28],
    "income": [50, 52, 49, 53, 51, 2000]
})

cleaned = remove_outliers_zscore_df(df, cutoff=2.0)
print(cleaned)

['age', 'income']
age        73.333333
income    375.833333
dtype: float64
age       111.061544
income    795.677175
dtype: float64
        age    income
0 -0.435194 -0.409504
1 -0.417186 -0.406991
2 -0.399178 -0.410761
3 -0.381170 -0.405734
4  2.040910 -0.408248
5 -0.408182  2.041238
   age  income
0   25      50
1   27      52
2   29      49
3   31      53


In [15]:
import numpy as np
import pandas as pd
def remove_outliers_zscore_df_new(df, cutoff=3.0, columns=None):
    """
    Remove outliers from a DataFrame using Z-score.
    
    A row is removed if ANY of the chosen columns
    has |z| > cutoff for that column.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        cutoff (float): Z-score threshold, default = 3.0.
        columns (list or None):
            List of numeric columns to check.
            If None, all numeric columns are used.

    Returns:
        pd.DataFrame: Cleaned DataFrame with outlier rows removed.
    """
    print(df)
    if columns is None:
        columns = df.select_dtypes(include=[np.number]).columns.tolist()
    print(columns)
    df_clean = df.copy()
    print(df_clean)
    #mask = pd.Series()
    for col in columns:
        # Calculate mean and std per column
        mean = df_clean[col].mean()
        print("column:", col)
        print("mean:", mean)
        std = df_clean[col].std()
        print("std:", std)
        # Avoid division by zero
        #std_replaced = std.replace(0, np.nan)

        # Compute Z-scores
        zscores = (df_clean[col] - mean) / std
        print("zscore:", zscores)
        # Keep rows where ALL columns satisfy |z| <= cutoff
        mask = (np.abs(zscores) <= cutoff)
        print("mask:", mask)
        #df_clean[col]=df_clean.loc[mask, col] 
        df_clean=df_clean[mask]
        #print(df_clean[mask])
    return df_clean


df = pd.DataFrame({
    "age": [25, 27, 29, 31, 300, 28],
    "income": [50, 52, 49, 53, 51, 2000]
})

cleaned = remove_outliers_zscore_df_new(df, cutoff=1.5)
print(cleaned)

   age  income
0   25      50
1   27      52
2   29      49
3   31      53
4  300      51
5   28    2000
['age', 'income']
   age  income
0   25      50
1   27      52
2   29      49
3   31      53
4  300      51
5   28    2000
column: age
mean: 73.33333333333333
std: 111.06154449973522
zscore: 0   -0.435194
1   -0.417186
2   -0.399178
3   -0.381170
4    2.040910
5   -0.408182
Name: age, dtype: float64
mask: 0     True
1     True
2     True
3     True
4    False
5     True
Name: age, dtype: bool
column: income
mean: 440.8
std: 871.6207317405891
zscore: 0   -0.448360
1   -0.446066
2   -0.449507
3   -0.444918
5    1.788851
Name: income, dtype: float64
mask: 0     True
1     True
2     True
3     True
5    False
Name: income, dtype: bool
   age  income
0   25      50
1   27      52
2   29      49
3   31      53


In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("ecommerceDataset.csv")

In [3]:
dataset.describe()

,Household,"Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room."
count,50424,50423
unique,4,27801
top,Household,Think & Grow Rich About the Author NAPOLEON HI...
freq,19312,30


In [5]:
dataset.info

<bound method DataFrame.info of          Household  \
0        Household   
1        Household   
2        Household   
3        Household   
4        Household   
...            ...   
50419  Electronics   
50420  Electronics   
50421  Electronics   
50422  Electronics   
50423  Electronics   

      Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We pri

In [ ]:
df['text_column'] = df['text_column'].astype(str)