In [1]:
from sklearn.linear_model import LogisticRegression

In [4]:
??LogisticRegression

In [5]:
l=[1,2,3,4,5]

In [9]:
o=[]
for i in l:
    if i >2:
        o.append(i)
print(o)

[3, 4, 5]


In [11]:
o = [i for i in l if i > 2]

In [12]:
print(o)

[3, 4, 5]


In [1]:
import numpy as np

In [2]:
b = np.array([(1,2,3), (4,5,6)], dtype = float)

In [3]:
b[:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
b[:,1]

array([2., 5.])

In [5]:
b[0,:]

array([1., 2., 3.])

In [6]:
b[:-1]

array([[1., 2., 3.]])

In [7]:
b[-1:]

array([[4., 5., 6.]])

In [8]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype = float)

In [9]:
c[:-1]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
c[-1:]

array([[7., 8., 9.]])

In [11]:
c[:,-1]

array([3., 6., 9.])

In [12]:
c[-1,:]

array([7., 8., 9.])

In [15]:
c[2,2]=10.0

In [16]:
c

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 10.]])

In [17]:
np.max(c)

10.0

In [18]:
np.amax(c)

10.0

In [19]:
e = np.array([[1,2,3], [4,5,6], dtype = float)

SyntaxError: invalid syntax (<ipython-input-19-52cb7604bb88>, line 1)

In [20]:
import pandas as pd

#initialize a dataframe
df = pd.DataFrame(
	[[21, 72, 67],
	[23, 78, 69],
	[32, 74, 56],
	[52, 54, 76]],
	columns=['a', 'b', 'c'])

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
type(c)

numpy.ndarray

In [23]:
f= df.values

In [24]:
f

array([[21, 72, 67],
       [23, 78, 69],
       [32, 74, 56],
       [52, 54, 76]], dtype=int64)

In [25]:
type(f)

numpy.ndarray

In [30]:
g= df.to_numpy()

In [31]:
type(g)

numpy.ndarray

In [32]:
g

array([[21, 72, 67],
       [23, 78, 69],
       [32, 74, 56],
       [52, 54, 76]], dtype=int64)

In [37]:
h= df.values()

TypeError: 'numpy.ndarray' object is not callable

In [40]:
??pd.merge

In [8]:
c=['oh', 'yea', 'makes', 'sense']

In [9]:
print(' '.join(word) for word in c)

<generator object <genexpr> at 0x000002AD813893C8>


In [13]:
print([' '.join(word) for word in c])

['o h', 'y e a', 'm a k e s', 's e n s e']


In [14]:
print([' '.join(c)])

['oh yea makes sense']


In [15]:
print(' '.join(c))

oh yea makes sense


Unpacking operator

In [31]:
list1 = [1,2,3]
list2 = [4,5,6]
new_list = [*list1, *list2]
print(new_list)

[1, 2, 3, 4, 5, 6]


In [32]:
list1.extend(list2)
print(list1)

[1, 2, 3, 4, 5, 6]


In [33]:
newlist = [x>3 for x in list1]

In [34]:
print(newlist)

[False, False, False, True, True, True]


In [36]:
newlist1 = [x for x in list1 if x > 2]
print(newlist1)

[3, 4, 5, 6]


In [37]:
dict1 = {'a':1 , 'b':2}
dict2 = {'c':3 , 'd':4}

In [39]:
newdict = {**dict1,**dict2}
print(newdict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [41]:
dict3 ={}
for key, value in dict1.items():
    dict3[key]=value
for key, value in dict2.items():
    dict3[key]=value
print(dict3)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [45]:
print(dict3.values())
print(type(dict3.values()))
print(list(dict3.values()))

dict_values([1, 2, 3, 4])
<class 'dict_values'>
[1, 2, 3, 4]


In [46]:
print(dict3.keys())
print(type(dict3.keys()))
print(list(dict3.keys()))

dict_keys(['a', 'b', 'c', 'd'])
<class 'dict_keys'>
['a', 'b', 'c', 'd']


In [47]:
print(dict3.items())
print(type(dict3.items()))
print(list(dict3.items()))

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
<class 'dict_items'>
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]


zip

In [52]:
list1 = [1,2,3]
list2 = [4,5,6]
list3=list(zip(list1,list2))

In [53]:
print(list3)

[(1, 4), (2, 5), (3, 6)]


In [57]:
l1 = ["eat","sleep","repeat"]
s1 ='geeks'

for elem in enumerate(s1):
    print(elem)
    
for count,elem in enumerate(s1):
    print(count,elem)
# printing the tuples in object directly
for ele in enumerate(l1):
    print (ele)

# changing index and printing separately
for count,ele in enumerate(l1,100):
    print (count,ele)

(0, 'g')
(1, 'e')
(2, 'e')
(3, 'k')
(4, 's')
0 g
1 e
2 e
3 k
4 s
(0, 'eat')
(1, 'sleep')
(2, 'repeat')
100 eat
101 sleep
102 repeat


In [55]:
s1 = 'abc'
s2 = 'efg'
list(zip(s1,s2))

[('a', 'e'), ('b', 'f'), ('c', 'g')]

In [58]:
" ".join('geeks')

'g e e k s'

In [60]:
"".join(['g', 'e', 'e', 'k', 's'])

'geeks'