In [ ]:
5
5 4
5 4 3
5 4 3 2
5 4 3 2 1


In [27]:
for j in range(5,0,-1):
    
    for i in range(5,j-1,-1):
        print(i,end =' ')
    print("")
    

5 
5 4 
5 4 3 
5 4 3 2 
5 4 3 2 1 


In [19]:
s = "Frustration leads to anger, anger leads to demotivated spirit, it leads to unhealthy mind and finally it leads to death"


In [26]:
from collections import Counter
def mostrepeated(s):
    list1 = s.split()
    
    count = Counter(list1)
        
    print(list1)
    print(dict(count))
  
mostrepeated(s)

['Frustration', 'leads', 'to', 'anger,', 'anger', 'leads', 'to', 'demotivated', 'spirit,', 'it', 'leads', 'to', 'unhealthy', 'mind', 'and', 'finally', 'it', 'leads', 'to', 'death']
{'Frustration': 1, 'leads': 4, 'to': 4, 'anger,': 1, 'anger': 1, 'demotivated': 1, 'spirit,': 1, 'it': 2, 'unhealthy': 1, 'mind': 1, 'and': 1, 'finally': 1, 'death': 1}


In [1]:
import numpy as np

In [4]:
r = np.ones((3,3))

In [5]:
g = r*2 

In [6]:
b = r*3

In [7]:
r

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
g

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [9]:
b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
n=np.array([[[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]],
       [[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]],
       [[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]]])

In [12]:
n

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [45]:
maximum1 =np.amax(n, axis = 0)

In [46]:
maximum1

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [31]:
max_channels = np.maximum(r, b)

In [32]:
print(max_channels)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [27]:
 np.maximum.reduce([r,g,b])

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [38]:
r[(0,1)]=4

In [39]:
r

array([[1., 4., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
 np.maximum.reduce([r,g,b])

array([[3., 4., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [47]:
avg=(r+g+b)/3

In [48]:
avg

array([[2., 3., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [4]:
# Python code to find key with Maximum value in Dictionary
  
# Dictionary Initialization
Tv = {'BreakingBad':100, 'GameOfThrones':1292, 'TMKUC' : 88}
 
Keymax = max(zip(Tv.values(), Tv.keys()))[1]
print(list(zip(Tv.values(), Tv.keys())))
print(Keymax)

[(100, 'BreakingBad'), (1292, 'GameOfThrones'), (88, 'TMKUC')]
GameOfThrones


In [6]:
my_list = [(107, 'a'),  (105, 'ab'), (100, 'abc')]
print(max(my_list))
print(dict(my_list))

(107, 'a')
{107: 'a', 105: 'ab', 100: 'abc'}


In [6]:
z=set(['abc'])

z.add('san')

z.update(['p','q'])

print(z)

{'q', 'san', 'p', 'abc'}
