In [1]:
import numpy as np

In [2]:
b = np.array([(1,2,3), (4,5,6)], dtype = float)

In [3]:
b[:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
b[:,1]

array([2., 5.])

In [5]:
b[0,:]

array([1., 2., 3.])

In [6]:
b[:-1]

array([[1., 2., 3.]])

In [7]:
b[-1:]

array([[4., 5., 6.]])

In [8]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype = float)

In [9]:
c[:-1]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
c[-1:]

array([[7., 8., 9.]])

In [11]:
c[:,-1]

array([3., 6., 9.])

In [12]:
c[:,2]

array([3., 6., 9.])

In [13]:
c[-1,:]

array([7., 8., 9.])

In [14]:
c[2,2]=10.0

In [15]:
c

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 10.]])

In [16]:
np.max(c)

10.0

In [17]:
np.amax(c)

10.0

In [18]:
e = np.array([[1,2,3], [4,5,6]], dtype = float)

In [19]:
e

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
a=np.ones((2,3))
b=np.ones((3,1))

In [51]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
b

array([[1.],
       [1.],
       [1.]])

In [55]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
b=np.array([[7],[8],[9]])
b

array([[7],
       [8],
       [9]])

In [57]:
c=a.T
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
d=c*b
d

array([[ 7, 28],
       [16, 40],
       [27, 54]])

In [73]:
r = np.ones((3,3))
r

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
g = r*2 
g

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [72]:
b = r*3
b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [74]:
n=np.array([[[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]],
       [[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]],
       [[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]]])

n

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [75]:
maximum1 =np.amax(n, axis = 0)
maximum1

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [76]:
max_channels = np.maximum(r, b)
max_channels

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [77]:
 np.maximum.reduce([r,g,b])

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [78]:
avg=(r+g+b)/3
avg

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [59]:
import random

In [60]:
random.seed(10)
z=random.random()
z

0.5714025946899135

In [61]:
x = random.sample(range(10, 30), 10)
y = random.sample(range(100, 300), 10)

In [62]:
x

[23, 25, 10, 16, 24, 29, 17, 14, 20, 12]

In [63]:
y

[108, 233, 225, 183, 119, 163, 290, 192, 111, 207]

In [64]:
from sklearn import linear_model

In [65]:
# Create linear regression object
regr = linear_model.LinearRegression()

In [66]:
import numpy as np
x_train = np.array(x)
y_train = np.array(y)

In [67]:
x_train=x_train.reshape(-1,1)

In [68]:
# Train the model using the training sets
regr.fit(x_train, y_train)

LinearRegression()

In [69]:
print(regr.coef_)

[-4.03757225]


In [20]:
import pandas as pd

#initialize a dataframe
df = pd.DataFrame(
	[[21, 72, 67],
	[23, 78, 69],
	[32, 74, 56],
	[52, 54, 76]],
	columns=['a', 'b', 'c'])

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
type(e)

numpy.ndarray

In [23]:
f= df.values

In [24]:
f

array([[21, 72, 67],
       [23, 78, 69],
       [32, 74, 56],
       [52, 54, 76]], dtype=int64)

In [25]:
type(f)


numpy.ndarray

In [26]:
g= df.to_numpy()

In [27]:
type(g)

numpy.ndarray

In [28]:
g

array([[21, 72, 67],
       [23, 78, 69],
       [32, 74, 56],
       [52, 54, 76]], dtype=int64)

In [29]:
df

,a,b,c
0,21,72,67
1,23,78,69
2,32,74,56
3,52,54,76


In [30]:
df.values()

TypeError: 'numpy.ndarray' object is not callable

In [31]:
df.values

array([[21, 72, 67],
       [23, 78, 69],
       [32, 74, 56],
       [52, 54, 76]], dtype=int64)

In [32]:
??pd.merge

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'str' = 'inner',
    on: 'IndexLabel | None' = None,
    left_on: 'IndexLabel | None' = None,
    right_on: 'IndexLabel | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool' = True,
    indicator: 'bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null

In [33]:
df = pd.DataFrame({'a': [10, 100, 1000], 'b': [20, 200, 2000], 'c': [30, 300, 3000]})
df

,a,b,c
0,10,20,30
1,100,200,300
2,1000,2000,3000


In [34]:
df['a']+10

0      20
1     110
2    1010
Name: a, dtype: int64

In [35]:
df['a']=df['a']+10

In [36]:
df

,a,b,c
0,20,20,30
1,110,200,300
2,1010,2000,3000


In [37]:
df['b']=df['b'].apply(lambda x:x+20)
df

,a,b,c
0,20,40,30
1,110,220,300
2,1010,2020,3000


In [38]:
df['c'].applymap(lambda x:x+20)

AttributeError: 'Series' object has no attribute 'applymap'

In [39]:
df['c'] = df.applymap(lambda x:x+20).loc[:, 'c']
df

,a,b,c
0,20,40,50
1,110,220,320
2,1010,2020,3020


In [40]:
df['d']=df['b']+df['c']
df

,a,b,c,d
0,20,40,50,90
1,110,220,320,540
2,1010,2020,3020,5040


In [41]:
df['e'] = df[['c','d']].apply(lambda x,y:x+y , axis=1)

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [42]:
# Iterating over one column - `f` is some function that processes your data
#result = [f(x) for x in df['col']]
# Iterating over two columns, use `zip`
f = lambda x,y : x+y
result = [f(x,y) for x, y in zip(df['c'], df['d'])]

In [43]:
print(result)

[140, 860, 8060]


In [44]:
df['e'] = pd.DataFrame(result, columns =['e'])
df

,a,b,c,d,e
0,20,40,50,90,140
1,110,220,320,540,860
2,1010,2020,3020,5040,8060


In [45]:
import math

In [46]:
df['f']= math.sqrt(df['d']*df['e'])

TypeError: cannot convert the series to <class 'float'>

In [47]:
# Iterating over two columns, use `zip`
f = lambda x,y : math.sqrt(x*y)
result = [f(x,y) for x, y in zip(df['d'], df['e'])]

In [48]:
df['f'] = pd.DataFrame(result, columns =['f'])
df

,a,b,c,d,e,f
0,20,40,50,90,140,112.249722
1,110,220,320,540,860,681.469001
2,1010,2020,3020,5040,8060,6373.570428
